author:
  name: Nelson Dane
  headline: "Technology and Project Blog"
  bio: "I make computers do things."
  links:
    - github: "https://github.com/NelsonDane"
    - linkedin: "https://www.linkedin.com/in/nelsondane/"
