main:
  - name: "Posts"
    pageRef: "/posts/"
    weight: 10
  - name: "Series"
    pageRef: "/series/"
    weight: 10
  - name: "Tags"
    pageRef: "/tags/"
    weight: 10
  - identifier: "github"
    pre: "github"
    url: "https://github.com/NelsonDane"
    weight: 30
  - identifier: "linkedin"
    pre: "linkedin"
    url: "https://www.linkedin.com/in/nelsondane/"
    weight: 30
  - identifier: "rss"
    pre: "rss"
    url: "/index.xml"
    weight: 30

footer:
  - name: "Posts"
    pageRef: "/posts/"
    weight: 20
  - name: "Series"
    pageRef: "/series/"
    weight: 20
  - name: "Tags"
    pageRef: "/tags/"
    weight: 20
