baseURL: "https://blog.nelsondane.me"
languageCode: en-us
title: "Nelson's Blog"
theme: "PaperMod"
enableEmoji: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

services:
  googleAnalytics:
    ID: G-Q7JXDTJ87P

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Nelson's Blog"
  description: "Technology and Project Blog"
  keywords: [Blog, Portfolio, Technology]
  author: Nelson Dane
  defaultTheme: auto

outputs:
  home:
    - HTML
    - RSS
    - JSON
