name: Use Lychee to Check for Dead/Broken Links

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/security.yaml
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lychee:
    name: Check for Dead/Broken Links
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Needed to comment on PRs
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Run Lychee
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2
        id: lychee
        with:
          format: markdown
          args: content/posts/**/*.md --root-dir content -a 200,403 --verbose
          fail: false

      - name: Comment broken links
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3
        with:
          path: lychee/out.md

      - name: Fail if broken links found
        if: steps.lychee.outputs.exit_code != 0
        run: exit 1
